#!/usr/bin/env python

import os,sys

if os.environ.has_key('CYGWIN'):
	os.environ['MAYA_PLUG_IN_PATH'] += os.path.pathsep+os.popen('cygpath -wa ./python').readlines()[0].strip()
	os.environ['SLUM_SEARCH_PATH'] 	= os.popen('cygpath -wa ./shader').readlines()[0].strip()
else:
	os.environ['MAYA_PLUG_IN_PATH'] += os.path.pathsep+os.popen('echo `pwd`/python').readlines()[0].strip()
	os.environ['SLUM_SEARCH_PATH'] 	= os.popen('echo `pwd`/shader').readlines()[0].strip()


scene = ''
if len(sys.argv)-1:
	scene = sys.argv[1]
os.system('maya %s' % scene)
